<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <RootNamespace>Digital_Scholarship_Management_System.API</RootNamespace>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.102.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
			<IncludeAssets>
				runtime; build; native; contentfiles; analyzers; buildtransitive
			</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
	</ItemGroup>

</Project>
